---

- name: M307609 - Add unused protocols to blacklist
  lineinfile:
    dest: /etc/modprobe.d/blacklist.conf
    create: yes
    state: present
    line: "blacklist {{item}}"
  with_items:
    - sctp
    - dccp

